### PR TITLE
Implement `cycle` iterator adapter 

### PR DESCRIPTION
**Pull request by alisomay**
This is an attempt to implement `cycle` iterator adapter as described in #116.

### CODE REVIEW

**Comment by irh** [comment]
Nice one @alisomay, this looks good, thanks!

Two things would make this complete:
- Documentation in [docs/reference/core_lib/iterator.md](https://github.com/koto-lang/koto/blob/ad94ce9e197267d7983b52bbd0a9ad0b19c2b235/docs/reference/core_lib/iterator.md) for the new function.
- Tests in [src/runtime/tests/iterator_tests.rs](https://github.com/koto-lang/koto/blob/ad94ce9e197267d7983b52bbd0a9ad0b19c2b235/src/runtime/tests/iterator_tests.rs) for anything that you think needs to be tested, I'd suggest at least checking that `.copy()` works as expected.

If you don't have time to add these extra bits then please let me know, I'll be happy to merge this PR as is and then I'll add the extras as a followup, up to you.

**Comment by alisomay** [comment]
You're welcome. Always a pleasure to work on this code base!
I'd love to add them.

**Comment by irh** [comment]
The documentation looks good. Sorry I wasn't clear enough but so far the tests for copy and other edge cases have gone into the [`.rs` test file](https://github.com/koto-lang/koto/blob/ad94ce9e197267d7983b52bbd0a9ad0b19c2b235/src/runtime/tests/iterator_tests.rs) I linked to above, rather than the `.koto` tests, which at this point are more for demonstration/discovery purposes.

**Comment by alisomay** [comment]
Oh I didn't realize that.
Good to know, will update accordingly.

**Comment by irh** [comment]
Thanks Ali! I have a couple of tweaks that I would add, do you have the 'Allow edits from maintainers' checkbox enabled?

**Comment by alisomay** [comment]
Yep! That's enabled, go ahead.

**Comment by irh** [comment]
Nice, I finally figured out the right git incantation =)

**Pull request merged**
